# Generated by Django 4.1.5 on 2023-01-26 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devices',
            options={'ordering': ['id'], 'verbose_name': 'Мобильные устройства', 'verbose_name_plural': 'Мобильные устройства'},
        ),
    ]
